baseURL = "https://tomwei7.com"
languageCode = "zh-cn"
title = "围城"
paginate = 5
theme = "stack"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true

disqusShortname = "tomwei7"
googleAnalytics = "UA-72226462-1"
uglyURLs = true

[permalinks]
post = "/:year/:month/:day/:filename"
page = "/:filename/"

[params]
mainSections = ["post"]
featuredImageField = "image"
rssFullContent = true
favicon = "/favicon.ico"

[params.comments]
enabled = true
provider = "disqus"

[params.sidebar]
subtitle = "程序员-代码-吐槽"
[params.sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"
[params.article]
math = false
toc = true
readingTime = true
[params.article.license]
enabled=true
default="Licensed under CC BY-NC-SA 4.0"
[params.footer]
since = "2016"
customText = ""

[params.dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"
