baseURL = "https://tomwei7.com"
title = "围城"
paginate = 16
theme = "m10c"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
disqusShortname = "tomwei7"
googleAnalytics = "UA-72226462-1"
copyright = "2021 Tomwei7 All rights reserved"
rssLimit = 20

[author]
name = "weicheng"
email = "tomwei7g@gmail.com"

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2
#[[menu.main]]
#identifier = "about"
#name = "About"
#url = "/about/"
#weight = 3

[params]
author = "围城"
description = "程序员-代码-吐槽"
menu_item_separator = " - "
avatar = "/avatar.webp"

[permalinks]
post = "/:year/:month/:day/:filename"
page = "/:filename/"

#[params.style]
#darkestColor = "#d35050"
#darkColor = "#212121"
#lightColor = "#f5e3e0"
#lightestColor = "#f5f5f5"
#primaryColor = "#ffffff"

#[params]
#mainSections = ["post"]
#featuredImageField = "image"
#rssFullContent = true
#favicon = "/favicon.ico"
#
#[params.comments]
#enabled = true
#provider = "disqus"
